<a href="https://colab.research.google.com/github/Saksham040402/ML_Praticals/blob/main/Welcome_To_Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_iris;
iris=load_iris();
data=iris.data;
import pandas as pd;
x=pd.DataFrame(data=data,columns=iris.feature_names)
# print(x)
y = pd.DataFrame(data=iris.target)
y.shape
# print(y)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size =0.4)


print(x_train.shape)
print(y_train.shape)

print(x_test.shape)
print(y_test.shape)

from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(max_depth=7, random_state=1)



dt.fit(x_train,y_train)



y_pred = dt.predict(x_test)
y_pred


from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_pred,y_test))
print(confusion_matrix(y_pred,y_test))
print(classification_report(y_pred,y_test))


(90, 4)
(90, 1)
(60, 4)
(60, 1)
0.9333333333333333
[[21  0  0]
 [ 0 19  0]
 [ 0  4 16]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       0.83      1.00      0.90        19
           2       1.00      0.80      0.89        20

    accuracy                           0.93        60
   macro avg       0.94      0.93      0.93        60
weighted avg       0.94      0.93      0.93        60



In [ ]:
import pandas as pd

df=pd.read_csv("diabetes.csv") 
df.head()
X=df.drop(columns='Outcome')
Y=df[['Outcome']]
from sklearn.model_selection import train_test_split 
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=.1,random_state=33) 
from sklearn.naive_bayes import GaussianNB
NB=GaussianNB(); 
NB.fit(X_train,Y_train); 
y_predict=NB.predict(X_test); 
from sklearn.metrics import accuracy_score,confusion_matrix 

acc=accuracy_score(y_predict,Y_test); 

con=confusion_matrix(y_predict,Y_test); 

print(acc); 

print(con);

0.7402597402597403
[[39 11]
 [ 9 18]]


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
from sklearn.datasets import load_iris;
iris=load_iris();
data=iris.data;
import pandas as pd;
x=pd.DataFrame(data=data,columns=iris.feature_names)
# print(x)
y = pd.DataFrame(data=iris.target)
y.shape
# print(y)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size =0.4)

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=4)



knn.fit(x_train,y_train)



y_pred = knn.predict(x_test)
y_pred




from sklearn.metrics import accuracy_score,confusion_matrix
print(accuracy_score(y_pred,y_test))
print(confusion_matrix(y_pred,y_test))

0.9666666666666667
[[16  0  0]
 [ 0 24  1]
 [ 0  1 18]]


/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [ ]:
from sklearn.datasets import load_iris;
import numpy as np
iris=load_iris();
data=iris.data;
import pandas as pd;
x=pd.DataFrame(data=data,columns=iris.feature_names)
# print(x)
y = pd.DataFrame(data=iris.target)
y.shape
# print(y)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size =0.4)

from sklearn.linear_model import LinearRegression

knn = LinearRegression()



knn.fit(x_train,y_train)



y_pred = np.argmax(knn.predict(x_test), axis=-1)
y_pred

from sklearn.metrics import accuracy_score,confusion_matrix
print(accuracy_score(y_pred,y_test))
print(confusion_matrix(y_pred,y_test))


0.4666666666666667
[[28 20 12]
 [ 0  0  0]
 [ 0  0  0]]
